### ISSUE TITLE
random test failure in CI

### ISSUE THREAD

**Issue by boustrophedon** [boustrophedon/extrasafe#32]
https://github.com/boustrophedon/extrasafe/actions/runs/6854741650/attempts/1

```

     Running unittests examples/ipc_server_with_database.rs (target/x86_64-unknown-linux-gnu/debug/examples/ipc_server_with_database-149f5286d0c62e1a)

running 1 test

running 1 test

running 1 test

running 1 test
test run_main ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 1 test
test run_main ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 1 test
test run_main ... FAILED

failures:

---- run_main stdout ----
main args: ["read_client-subprocess", "run_main", "--", "--sub", "read_client"]
about to make read request to webserver
thread 'run_main' panicked at examples/ipc_server_with_database.rs:324:9:
assertion `left == right` failed
  left: "hellowrite extrasafe"
 right: "hello\nextrasafe"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    run_main

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.07s

test run_main ... FAILED

failures:

---- run_main stdout ----
main args: ["/home/runner/work/extrasafe/extrasafe/target/x86_64-unknown-linux-gnu/debug/examples/ipc_server_with_database-149f5286d0c62e1a"]
thread 'run_main' panicked at examples/ipc_server_with_database.rs:401:5:
client3 exited unsuccessfully: ExitStatus(unix_wait_status(25856))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    run_main

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.29s

error: test failed, to rerun pass `--example ipc_server_with_database`
```

This is very strange and I'm not really sure how it could happen. It did not occur when pulling locally and running, or when re-running CI.

**Comment by boustrophedon** [comment]
I disabled this test in CI but it would be nice to set up an extrasafe-examples crate or workspace that could be used instead. Or I guess just add an extra step in CI to run `cargo run --example ipc_server_with_database` (i.e. executing it as an example rather than a test), because CI would still fail if it panicked.

**Comment by boustrophedon** [comment]
https://github.com/boustrophedon/extrasafe/pull/37
